### ISSUE TITLE
Tested on  3160

### ISSUE THREAD

**Issue by shimuldn** [ammulder/AppleIntelWiFiMVM#3]
..

**Comment by Moustafasoliman** [comment]
I have 3160 i dont understand what u wrotr 
Is this kext work with intel 3160 ??

**Comment by pijussimke123** [comment]
On what mac os version did u install this kext???? i really need mac os version that u installed this kext on

**Comment by shimuldn** [comment]
I forget but will be the latest release on that date.

On Feb 14, 2017 1:23 AM, "pijussimke123" <notifications@github.com> wrote:

On what mac os version did u install this kext???? i really need mac os
version that u installed this kext on

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ammulder/AppleIntelWiFiMVM/issues/3#issuecomment-279503062>,
or mute the thread
