### ISSUE TITLE
Do you write drivers for?

### ISSUE THREAD

**Issue by oybekrustamov** [ammulder/AppleIntelWiFiMVM#40]
Hello everyone, those who are interested.
Can you write a driver for Qualcomm Atheros devices?
More than 2-3 million users have **QCA9377** card. I would like to see a driver for Mac OS from you. Many would be grateful for your work! Here I posted the necessary files (I think so), I think they will be useful to you .. Thank you!

[**this is repo(source) files**](https://github.com/oybekrustamov/qca9377_fully_source)

**Comment by influenist** [comment]
Hi, you could try you luck with @zxystd at https://github.com/OpenIntelWireless/

**Comment by oybekrustamov** [comment]
> Hi, you could try you luck with @zxystd at https://github.com/OpenIntelWireless/

Ok, thank you
